### ISSUE TITLE
Proxy single file

### ISSUE THREAD

**Issue by blackliner** [NginxProxyManager/nginx-proxy-manager#1029]
I would like to do something similar to get.docker.com, serve a static file that can be curl'd into bash to bootstrap some stuff. Is this possible with maybe custom nginx configs?

Preferably I would like to just forward this subdomain to a github raw file like this one:
https://github.com/blackliner/raspi_monitor/blob/main/install.sh

**Comment by p-fruck** [comment]
Hi,
I'm not working on this project but I might have a solution for you. Under `Proxy Hosts -> Custom locations` you can redirect a specific subfolder to another resource, eg. https://example.com/subfolder -> https://github.com/someblob
You can also set `/` to be the subfolder if you want to redirect example.com to the github blob.

Please let me know if this helped you :wink:

**Comment by blackliner** [comment]
Cool, it works for the page: setup.lauraundflorian.de

But I cant get the [raw version](https://raw.githubusercontent.com/blackliner/raspi_monitor/main/install.sh) to work, but might be a github issue

**Comment by p-fruck** [comment]
It seems to me like you are using a redirect host instead of a proxy host. Curl will (by default) not follow redirects. You can however tell curl to follow such redirects using `curl -L example.com`. If you use proxy hosts, you are not redirecting your http/s traffic, so it should work.
Keep in mind that you have to proxy your incoming http traffic to the raw github file! If you force SSL redirection on your host, you once again have to tell curl to use the `-L` flag!

**Comment by chaptergy** [comment]
Feature request: https://github.com/jc21/nginx-proxy-manager/issues/58

**Comment by chaptergy** [comment]
Maybe this helps: https://github.com/jc21/nginx-proxy-manager/issues/320

**Comment by blackliner** [comment]
> Maybe this helps: #320

sweet, that did it!! thanks alot!
