### ISSUE TITLE
DNS challenge provider request: web.gratisdns.dk

### ISSUE THREAD

**Issue by casperse** [NginxProxyManager/nginx-proxy-manager#1461]
**What provider would you like to see added to NPM?**

https://web.gratisdns.dk/

**Have you checked if a certbot plugin exists?**

I havent found one

**Comment by chaptergy** [comment]
Unfortunately the DNS challenge within nginx proxy manager is only available for [certbot dns plugins](https://certbot.eff.org/docs/using.html#dns-plugins). GratisDNS does not have a plugin for this. There is a [python library](https://github.com/laudrup/python-gratisdns/blob/master/gratisdns/gratisdns.py) which could be used to create a plugin, but it is very incomplete and missing lots of stuff in order to be actually used for a plugin. [Lexicon](https://github.com/AnalogJ/lexicon#supported-providers) does not support GratisDNS either, which would have made it easier to create a plugin.

So I don't think it is very likely to be implemented for now, unless a certbot plugin is published.

**Comment by binsentsu** [comment]
Not a solution, but a workaround for unsupported DNS providers: A certbot plugin is not always necessary. I'm just using ACME-DNS redirecting the dns_acmedns_api_url to a NodeRed flow, which exposes /update API endpoint and this flow updates TXT records through HTTP Request Node within my non-supported DNS provider.

**Comment by larskruckow** [comment]
gratisdns will shut down in the near future and migrate all customers to one.com.
[https://help.one.com/hc/en-us/articles/4417467033489-Ofte-stillede-sp%C3%B8rgsm%C3%A5l-om-migreringen-fra-GratisDNS-til-one-com](https://help.one.com/hc/en-us/articles/4417467033489-Ofte-stillede-sp%C3%B8rgsm%C3%A5l-om-migreringen-fra-GratisDNS-til-one-com)
Perhaps this issue is should be closed.

**Comment by chaptergy** [comment]
Allright, thanks for letting us know!
