### ISSUE TITLE
Reverse proxy with a path

### ISSUE THREAD

**Issue by Ferrox12** [NginxProxyManager/nginx-proxy-manager#1847]
Hi,
this is a question.
I have installed Nginx proxy manager on my terramaster nas on docker.
I have reserved a hostname (es. example.com) that point to my router. With that and with the port forwarding I reach the services I expone on the net (es. example.com:A, example.com:B).
Is it possible with the reverse proxy to reach them without entering the port but with a specific name? (es. example.com/A, example.com/B)

**Comment by AlthaTechnology** [comment]
I use this with docker swarm. You put in the service name and it is able to redirect to that stack/service without having to bind ports.

All of our entries use service names and most of them on port 80, I think this is what you are asking. Does that answer the question?

This may be swarm specific behavior, I'm not sure. Swarm does it's own loadbalancing through an internal DNS server.
[https://docs.docker.com/engine/swarm/ingress/](https://docs.docker.com/engine/swarm/ingress/)

**Comment by Ferrox12** [comment]
No.
At the moment I have installed Nginx Proxy Manager on docker and with a hostname that is CNAME type I reach one of my services. I would like to use only a hostname (es. example.com) to reach everyone of them (es. example.com/name1, example.com/name2).
I don't know if this is possible

**Comment by hoiber** [comment]
Hey Mate, 
I would suggest using subdomains rather than a url extension. eg name1.example.com instead of example.com/name1. This will allow you to set up DNS using the subdomain, doesn't have to be public unless you want the service to be available outside your local network (wouldn't recommend this would look at SD WAN or VPN solutions unless you need it available to others) but it will still work either way. The will allow you to enter the port and "link" it to the subdomain. 

![image](https://user-images.githubusercontent.com/51186531/154056232-789a34c4-f8b9-42ff-8ca5-d913e10b87fd.png)

**Comment by Ferrox12** [comment]
This is what I don't want to do. I don't want have a number of subdomains

**Comment by hoiber** [comment]
ah right, yeah i dont think it will work they way you want it to sorry.

**Comment by Ferrox12** [comment]
Thanks for the help
