### ISSUE TITLE
IONOS DNS Challenge, TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by AqujZ1K9** [NginxProxyManager/nginx-proxy-manager#1877]
Hi Guys,

I'm having trouble receiving an SLL Cert via IONOS DNS Challange.
This used to be working in the same Stup allready.
I am thankful for every hint.

Error: Command failed: certbot certonly --config "/etc/letsencrypt.ini" --cert-name "npm-23" --agree-tos --email "XXXX@XXXXX.XXX" --domains "*.XXXXX.XXX" --authenticator dns-ionos --dns-ionos-credentials "/etc/letsencrypt/credentials/credentials-23"
Saving debug log to /var/log/letsencrypt/letsencrypt.log
An unexpected error occurred:
TypeError: list indices must be integers or slices, not str
Ask for help or search for solutions at https://community.letsencrypt.org. See the logfile /var/log/letsencrypt/letsencrypt.log or re-run Certbot with -v for more details.

    at ChildProcess.exithandler (node:child_process:399:12)
    at ChildProcess.emit (node:events:520:28)
    at maybeClose (node:internal/child_process:1092:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)

Version:
 jc21/nginx-proxy-manager:2.9.16

**Expected behavior**
receiving an Wildcard SSL Cert. via Certbot using DNS Challenge.

**Operating System**
Debian 11

**Screenshots**
![proxymanagererror](https://user-images.githubusercontent.com/76105246/155121074-69deb196-71c2-4a5d-937b-b776bfe8fa3b.png)

**Comment by AqujZ1K9** [comment]
so this seems to be an issue with the IONOS script. I hat to delete the _acme-challenge TXT entry. After that it magically worked for me::

**Comment by Gortosch** [comment]
This workaround also works for me. Thanks!

**Comment by Nexow91** [comment]
Hello everyone, I'm having the same problem but I don't know where and how I need to change something so that the IONOS DNS Challenge works. From what I can tell, I need to delete the "_acme-challenge TXT" entry from the script for DNS Challenge IONOS.

Can anyone tell me where I can find this script and what it's called?

My goal was to use DNS Challenge via IONOS to roll out SSL locally for websites so that I can access it using a DNS name without error messages.

Greetings
