### ISSUE TITLE
How do I manually edit the Nginx config?

### ISSUE THREAD

**Issue by ScottBeeson** [NginxProxyManager/nginx-proxy-manager#1920]
I'm not familiar with docker _at all_. If I needed to manually add something to the config, how would I do so?

**Comment by mochman** [comment]
If you're talking about adding something to the individual site's proxy config.  You can do that in the Advanced Tab when you're editing the proxy. 
If you want to modify the main nginx.conf file, you can do what is talked [about here](https://github.com/NginxProxyManager/nginx-proxy-manager/tree/develop/docs/advanced-config#custom-nginx-configurations).

**Comment by ScottBeeson** [comment]
That helps, but is there no way to see the full config?

**Comment by mochman** [comment]
If you want to just see the nginx.conf file you can run `docker exec <PROXY_MANAGER_NAME> cat /etc/nginx/nginx.conf`

If you really want to mess around with the config, you can always mount the `/etc/nginx/nginx.conf` file.  You'll need to have a fully configured `nginx.conf` file already on your local server before you do this, otherwise you'll erase the one in the docker container.  You can probably use the [one in this repo](https://github.com/NginxProxyManager/nginx-proxy-manager/blob/1f3ac7a9ec80ec49a1c13ebcc46ab3f48ae026f4/docker/rootfs/etc/nginx/nginx.conf).

You can add this to your `docker-compose.yml` 
```
volumes:
  # Stuff already in your volumes section.
  - ./path/to/your/nginx.conf:/etc/nginx/nginx.conf
```

I don't recommend doing this, but if you want full access to that file, this is a way to do it.
