### ISSUE TITLE
SFTP Downloads using Apache Guacamole behind NPM

### ISSUE THREAD

**Issue by Baipyrus** [NginxProxyManager/nginx-proxy-manager#2053]
I have posted about my Problem on Reddit before, but even after 600+ Views and almost a month of waiting, nobody seemed to be able to help. Please read the detailed description and my observations from the post linked below:

https://www.reddit.com/r/nginxproxymanager/comments/u8pfe9/sftp_downloads_using_apache_guacamole_behind_npm/

**Comment by the1ts** [comment]
All I can think of is that when you are going through NPM, your router and ISP network comes into play. In the past I've seen this slow down when a part of the network stack changes the TCP window scaling values (the amount of packets to be sent before a response is required), if this is set lowered by one piece of networking equipment in the route we can get down to modem speeds quickly on a broadband network when large single transfers are attempted. (Speed of transfer goes up as the TCP Window is scaled up, this is why downloads ramp up in speed and fluctuate as sending is paused waiting for a response packet saying all receieved).
It would be good to test a simple large file transfer not via NPM but over the same network to isolate the issue. Worth using a host file to send traffic to the subdomain, but directly to NPM, rather than your ISP router and back in.

**Comment by Baipyrus** [comment]
I'm not sure I can follow what you are suggesting. The problem is not the speed of downloading as it instantly cuts the connection as soon as you try to download. This also only occurs on this SFTP Download, as the problem does not occur on any other subdomain or request in general (I use a Nextcloud alongside other things). Everything worked just fine up to this point. I've also said in the post before that any type of Download, even over SFTP on the same exact webpage, works just fine when I do it locally (in the same network), which is why I came to the conclusion that this problem has to do with NPM.

**Comment by the1ts** [comment]
Been struggling to grasp what the real problem is, but:
You don't mention setting up the NPM subdomain to allow web sockets. This is specifically mentioned as a requirement in the proxying guacamole section of the [docs](https://guacamole.apache.org/doc/0.9.7/gug/proxying-guacamole.html#nginx). Have you turned this feature on in the edit proxy host form in NPM?

**Comment by Baipyrus** [comment]
I'm not sure how I managed to fail this badly, but this seems to have been the problem. I am 100% certain that I have tried this in the past
