### ISSUE TITLE
SSL For IP shows localhost for everything

### ISSUE THREAD

**Issue by Anas-Sherif** [NginxProxyManager/nginx-proxy-manager#2062]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - No
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

**Nginx Proxy Manager Version**

**To Reproduce**
1. Go to 'SSL Certificates'
2. Add an SSL Certificate for an IP
3. Add the Certificates to your proxy host
4. Go to https:/<your ip>

**Expected behavior**

Using the certificate I specified for the IP

**Screenshots**

**Operating System**

**Additional context**

**Comment by Anas-Sherif** [comment]
![image](https://user-images.githubusercontent.com/77907877/169614998-1eebf323-4361-496a-806e-b1c518be5e43.png)

**Comment by the1ts** [comment]
So you have an IP based cert (with both CN and SAN pointing to IP) from one of the few CAs that allow that for public IPs still or you've created a self signed cert?
Because entering an IP into the Domain Name field in the Add Let's Encrypt form results in an error from Certbot that its an IP not a domain since letsencrypt do not allow IP certs.

**Comment by Anas-Sherif** [comment]
> So you have an IP based cert (with both CN and SAN pointing to IP) from one of the few CAs that allow that for public IPs still or you've created a self signed cert? Because entering an IP into the Domain Name field in the Add Let's Encrypt form results in an error from Certbot that its an IP not a domain since letsencrypt do not allow IP certs.

I'm using a custom certificate not one from Let's Encrpyt.

**Comment by the1ts** [comment]
I don't really know if this can be fixed on the nginxproxymanager side.

From my trials:

1. create a self signed cert with both CN and alt names 192.168.0.80
2. setup a new nginxproxymanager on that IP
3. add the self signed cert as a custom
4. setup a proxy_host that proxies domain 192.168.0.80 to 192.168.0.80:81 to get a working proxy_host of the npm interface
5. assigned the new custom SSL to that proxy_host.

The proxy_host/1.conf file looks good, has 192.168.0.80 as servername, the new custom_ssl cert and key and rest of proxy_conf pieces. Indeed on hitting https://192.168.0.80 what is displayed is the npm login screen so the new proxy_host config is being found and used for the proxy section.

Curl with host header to IP `curl -vik -H "Host: 192.168.0.80" https://192.168.0.80` gives the default nginxproxymanager self signed cert for localhost, not the cert for 192.168.0.80 server.
```
* Server certificate:
*  subject: O=localhost; OU=localhost; CN=localhost
*  start date: May 26 15:06:50 2022 GMT
*  expire date: May 23 15:06:50 2032 GMT
*  issuer: O=localhost; OU=localhost; CN=localhost
```
If I ask curl to use SNI to point at 192.168.0.80 `openssl s_client -connect 192.168.0.80:443 -servername 192.168.0.80` I get the self signed cert I created (note the CN = 192.168.0.80).

```
Certificate chain
 0 s:C = XX, ST = N/A, L = N/A, O = Self-signed certificate, CN = 192.168.0.80: Self-signed certificate
   i:C = XX, ST = N/A, L = N/A, O = Self-signed certificate, CN = 192.168.0.80: Self-signed certificate
```
This looks like the IP only SSL functionality is chosen before the server name is used to find the proxy config unless SNI is used, which makes sense since SNI was created to allow the host header info to be sent during SSL negotiation, allowing cert choosing on the server side.
Seems that browsers do not do SNI on IP only URLs, unless I'm much mistaken (Tested on both Chrome and Firefox). Curl can be convinced to send SNI for IP and works as hoped for.

**Comment by Anas-Sherif** [comment]
Alright thanks for the help.
