### ISSUE TITLE
Strange Issue with Proxy hosts "page isn’t redirecting properly" with SSL Cert

### ISSUE THREAD

**Issue by jeremyoha450** [NginxProxyManager/nginx-proxy-manager#2154]
Hi there

i have a strange problem where by if i use ssl cert (lets encrypt) on a proxy host

i get "this page isn’t redirecting properly"

if i dont use ssl cert. it works fine.

i'm new to this so i dont know alot of things

regards
jeremy

**Comment by jeremyoha450** [comment]
Update:

i can run SSL on every host but if i enable force SSL i get "this page isn’t redirecting properly"

i'm only a little disappointed in the total lack of replies/helps from here. 
a simple hey we only do the web interface for Nginx contact them directly.

regards.

**Comment by the1ts** [comment]
Jeremy,

You aren't getting any replies as there really isn't enough info to give any specific help. This looks to me like a configuration issue or setup confusion. You say in the first one that adding an SSL cert causes the error, in the second that its enabling force SSL that causes it.

Allowing us to take a look at how you have the proxy config setup for a failing host may be useful, also if you are using anything else such as cloudflare in front knowing this may help others diagnose the issue. You can drag and drop images into an issue comment, doing so may get more and hopefully helpful responses. Like others have done, show the proxy-config and any of the tabs you have touched for that proxy, you can blank out any domain details that are sensitive, but leave as much of the IP and ports so people can see any issues caused by that layer.

**Comment by jeremyoha450** [comment]
If more information was need a simple hey give more into please wouold of been great help.

Anyway i soloved it myself
