### ISSUE TITLE
configure in advanced

### ISSUE THREAD

**Issue by keivanipchihagh** [NginxProxyManager/nginx-proxy-manager#2257]
Hello there! I was wondering if it's possible to pre-configure the _Nginx-Proxy-Manager_ to have -for instance- a few **Proxy Hosts** when the container is created? I couldn't find anything related to this on the internet.
Thank you

**Comment by the1ts** [comment]
Not sure 100% sure what you are requesting but my thoughts below:

If you are using SQLlite rather than MySQL as the backing DB, you can simply have a copy of the NPM starter volumes with the required hosts already provisioned so NPM will start an existing config and password. If the certs are old, they will automatically be updated by the standard process.
If you are using MySQL, you will have to have MySQL and NPM volumes created with the Proxy Hosts and password you require so they are both provisioned with that data.

**Comment by keivanipchihagh** [comment]
Oh I did not know that. So having copied the preserved data should do the job?

**Comment by the1ts** [comment]
Since good container deployments keep their config and data outside the container to allow updates, yes if you follow the setup guide, all data will be in the volumes so can be plugged back in recovering back to the state when it was copied.

**Comment by keivanipchihagh** [comment]
Great! thank you! will test it asap.
