### ISSUE TITLE
Experiencing "Bad Gateway" error when trying to login to web UI

### ISSUE THREAD

**Issue by Robert-Clever** [NginxProxyManager/nginx-proxy-manager#2311]
I have seen several issues online of people that have ran into issues trying to connect to the web UI. Many people get the "Bad Gateway" error. I have done a lot of research and it doesn't seem like there is a clear cut solution to fix this. I have attached the docker compose file that I am using to start up the Proxy Manager. I replace the passwords with real ones when I go to start it up. Any help that you can provide would be greatly appreciated.

[docker_compose.txt](https://github.com/NginxProxyManager/nginx-proxy-manager/files/9739652/docker_compose.txt)

**Comment by Robert-Clever** [comment]
I have been trying to follow these instructions... https://www.youtube.com/watch?v=iFHbzWhKfuU. Seems like a few people in the comments have had similar issues, but again... no one really seems to have a resolution. If you need anymore information to further trouble shoot, just let me know and I can provide it to you.

**Comment by 407pilot** [comment]
I'll chime in and say that I am also experiencing this problem. More info if needed, just tell me what that info is.

**Comment by the1ts** [comment]
This looks like a docker config issue, that docker compose changes both the container port and exposed port for http from 80 to 82, are you changing /etc/nginx/conf.d/default.conf inside the container? If not then you have broken http. I guess you mean 82:80, i.e. port 80 still in the container, but exposed as port 82 on the host.

**Comment by skaag** [comment]
Yeah, I kinda gave up on this tool for now because of this issue. There's no clear documentation on how SSL is actually handled, how the hostname is obtained and used for the purpose of generating an SSL cert with LE, etc.. There's no good error reporting / testing, etc.

Don't get me wrong I think it's a great start and a good product to build which deserves to exist, and I might help and contribute code/scripts in my free time, but for now it's easier for me to just configure the environment myself since I know how to configure nginx with my eyes closed.

**Comment by Robert-Clever** [comment]
Closing this issue for now as I no longer using Nextcloud and am not experiencing this error anymore.
