### ISSUE TITLE
Nginx Proxy Manager was accidentally deleted after being recreated with portainer

### ISSUE THREAD

**Issue by cevinov** [NginxProxyManager/nginx-proxy-manager#2349]
Hello, sir,

I'm confused now that all my applications get an error **"Origin is unreachable Error code 523"**. This is because I removed the Nginx Proxy Manager container. How to solve this problem sir?

Thank you

**Comment by the1ts** [comment]
That is an error from Cloudflare that the setup endpoint cannot be reached, probably because you don't have anything listening now NPM has been removed/deleted.
Check the usual, DNS, router forwarding, container listening ports etc. Something somewhere is no longer lined up so cloudflare is being asked to forward the traffic to nowhere and refusing with this error.
