### ISSUE TITLE
Command failed: /usr/bin/htpasswd

### ISSUE THREAD

**Issue by headcrushed** [NginxProxyManager/nginx-proxy-manager#2691]
**Checklist**
- Have you pulled and found the error with `jc21/nginx-proxy-manager:latest` docker image?
  - Yes
- Are you sure you're not using someone else's docker image?
  - Yes
- Have you searched for similar issues (both open and closed)?
  - Yes

**Describe the bug**

When trying to add basicauth password for access list gui shows "internal error" and logs show [Express  ] › ⚠  warning   Command failed: /usr/bin/htpasswd

**Nginx Proxy Manager Version**

2.9.20

**To Reproduce**
1. Add new access list or modify old one with a basicauth
2. Add username & password
3. Click save

**Expected behavior**

GUI saves the access list.

**Screenshots**

**Operating System**

Docker with Debian Bullseye x64

**Additional context**

**Comment by Jamyz** [comment]
I have same error :
`[3/17/2023] [8:32:59 AM] [Access   ] › ℹ  info      Building Access file #5 for: Whitelist
[3/17/2023] [8:32:59 AM] [Access   ] › ℹ  info      Adding: Jamyz
[3/17/2023] [8:32:59 AM] [Access   ] › ✖  error     Error: Command failed: /usr/bin/htpasswd 
Usage:
	htpasswd [-cimBdpsDv] [-C cost] passwordfile username
	htpasswd -b[cmBdpsDv] [-C cost] passwordfile username password
	htpasswd -n[imBdps] [-C cost] username
	htpasswd -nb[mBdps] [-C cost] username password
 -c  Create a new file.
 -n  Don't update file; display results on stdout.
 -b  Use the password from the command line rather than prompting for it.
 -i  Read password from stdin without verification (for script usage).
 -m  Force MD5 encryption of the password (default).
 -B  Force bcrypt encryption of the password (very secure).
 -C  Set the computing time used for the bcrypt algorithm
     (higher is more secure but slower, default: 5, valid: 4 to 31).
 -d  Force CRYPT encryption of the password (8 chars max, insecure).
 -s  Force SHA encryption of the password (insecure).
 -p  Do not encrypt the password (plaintext, insecure).
 -D  Delete the specified user.
 -v  Verify password for the specified user.
On other systems than Windows and NetWare the '-p' flag will probably not work.
The SHA algorithm does not use a salt and is less secure than the MD5 algorithm.
    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)`

**Comment by andrew-s** [comment]
Also seeing this error - looks like it's specifically coming from; https://github.com/NginxProxyManager/nginx-proxy-manager/blob/fccbde1371adbe92c2d26047e4b451ceeb200232/backend/internal/access-list.js#L505

Looks like this was changed 18 days ago from `exec` to `execFile` - I'd those arguments aren't making it to the binary.

```
[3/17/2023] [8:41:20 AM] [Access   ] › ✖  error     Error: Command failed: /usr/bin/htpasswd 
Usage:
        htpasswd [-cimBdpsDv] [-C cost] passwordfile username
        htpasswd -b[cmBdpsDv] [-C cost] passwordfile username password

        htpasswd -n[imBdps] [-C cost] username
        htpasswd -nb[mBdps] [-C cost] username password
 -c  Create a new file.
 -n  Don't update file; display results on stdout.
 -b  Use the password from the command line rather than prompting for it.
 -i  Read password from stdin without verification (for script usage).
 -m  Force MD5 encryption of the password (default).
 -B  Force bcrypt encryption of the password (very secure).
 -C  Set the computing time used for the bcrypt algorithm
     (higher is more secure but slower, default: 5, valid: 4 to 31).
 -d  Force CRYPT encryption of the password (8 chars max, insecure).
 -s  Force SHA encryption of the password (insecure).
 -p  Do not encrypt the password (plaintext, insecure).
 -D  Delete the specified user.
 -v  Verify password for the specified user.
On other systems than Windows and NetWare the '-p' flag will probably not work.
The SHA algorithm does not use a salt and is less secure than the MD5 algorithm.

    at ChildProcess.exithandler (node:child_process:402:12)
    at ChildProcess.emit (node:events:513:28)
    at maybeClose (node:internal/child_process:1100:16)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:304:5)
```

**Comment by jc21** [comment]
This is fixed in the `github-develop` docker tag, and will be in the next release very soon
