### ISSUE TITLE
Can not proxy to Docker Host network ports

### ISSUE THREAD

**Issue by afzl-wtu** [NginxProxyManager/nginx-proxy-manager#3050]
I am runnign nginxproxymanger with following docker-compose.yaml file:
version: '3.8'
services:
  app:
    container_name: nginx
    network_mode: npm-nw
    ports:
      - '80:80'
      - '443:443'
    extra_hosts:
        - 'ss.ss:host-gateway'
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

I added two extra settings here. network_mode: npm-nw for proxying to other dockers on this bridge network. And extra_hosts: - 'ss.ss:host-gateway', So that I can access and proxy to wireguard-ui web interface at port 5000 and adguard web interface at port 5001. I can proxy to all dockers on npm-nw network but I get "502 Bad Gateway" when proxying to ss.ss:5000 or ss.ss:5001 in npm.
I also added ports 5000 and 5001 in firewall setting. I also confirm I can send messages tcp and udp through netcat on host from inside the npm container (nc ss.ss 5000 ).
I also confirm, from inside npm container I successfully get webpage of wireguard-ui with wget ss.ss:5000 with no error.
So it confirms There is no firewall issue and also webpage of wireguard-ui or adguard can be accessed inside npm container with wget. Only NPM gives error of 502 bad gateway.
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/64379149/9e03110b-5e9a-4bd8-b989-ceb3d56b3808)
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/64379149/e0f79116-8e83-4eac-9fe4-fb6ad7b08750)

My Config

I also used https mode but always 502 gate way
![image](https://github.com/NginxProxyManager/nginx-proxy-manager/assets/64379149/b6d28fe9-12cf-420d-ad8d-297cdd5bc42a)

All other webserver inside dockers on npm-nw are working fine.

**Comment by duchu** [comment]
I have same problem

**Comment by the1ts** [comment]
I think perhaps some more understanding of docker networking would be useful, I liked [this](https://www.youtube.com/watch?v=bKFMS5C4CG0) video discussion of all the types of networking, when to use them and what functionality is different between them all.
Saying a bridged network is insecure since it has access to both networks is not a security issue its the definition of a bridge in networking.

**Comment by afzl-wtu** [comment]
> I think perhaps some more understanding of docker networking would be useful, I liked [this](https://www.youtube.com/watch?v=bKFMS5C4CG0) video discussion of all the types of networking, when to use them and what functionality is different between them all. Saying a bridged network is insecure since it has access to both networks is not a security issue its the definition of a bridge in networking.

I create npm-nw network with command:
`docker network create npm-nw`
Is it still a bridge network? If so, how I can make it not bridged but only dockers only network.
Also what is the solution of ss.ss not resolved to host ip address but 10.7.0.1xx works fine.

**Comment by afzl-wtu** [comment]
> You are creating a bridge network see `docker network create --help`.

Thanks for your time. I watched the whole video now. It is informative but I do not like the speaking person. Its way of speaking is not- much clear. But Thank u.

**Comment by RemyDG0** [comment]
I have the same problem, the only short term solution I found was to fill the IP address of my machine. But I am soon to move my machine to another network and the IP range is not the same, I will have to change it in the fields of every proxy entry I made. 

Since I work within TrueNAS I already submitted this issue on their page but it seems that my issue is not linked to TrueNAS or that people there did not run in the same trouble as me...
https://github.com/truenas/apps/issues/2071

I am in a position I expect my issue to be in the category "too obvious to be seen"
