### ISSUE TITLE
502 Bad Gateway openresty

### ISSUE THREAD

**Issue by 404gods** [NginxProxyManager/nginx-proxy-manager#3423]
May I ask why my NPM reverse proxy to the local server container can only be accessed via 172.17.0.1:port, and if I use 127.0.0.1:port, it will result in a 502 Bad Gateway openresty error? This issue also occurs when reverse proxying non-container services, where I cannot use 127.0.0.1:port and must instead use the actual IP address of my machine followed by the port number, otherwise a 502 error is returned. What could be causing this problem? Thank you.

**Comment by andmpel** [comment]
How did you fix it!?

**Comment by NULL-Response** [comment]
Because of docker, u should use ip of docker0 (`ip show addr docker0`), normally 172.17.0.1
Best practice: put NPM and other docker-services under the same network (like `docker network create NPM_group`), add:
```
networks:
  default:
    external: true
    name: NPM_group
```
in docker-compose.yml if other services aint `network_mode: host`. 

My advise if ur NPM and other services (for example, service b) are in the same host:
1. b isnt `network_mode: host`, then use container name as NPM IP;
2. b is  `network_mode: host` ,or didnt join the same network as NPM, then use 172.17.0.1 (and `ufw allow port comment "container_name"`);
3. b is on another computer, then use frp.
